In [1]:
import numpy as np
import torch

In [4]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)
print(data, type(data))
print(data_tensor, type(data_tensor))

[[1, 2], [3, 4]] <class 'list'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [3]:
data = [[1,2],[3,4],[5,6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [5]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [11]:
rand = torch.rand(3,4,5)
rand

tensor([[[0.6418, 0.0201, 0.8284, 0.7265, 0.1945],
         [0.4629, 0.1228, 0.4321, 0.3722, 0.1647],
         [0.6573, 0.4516, 0.7172, 0.3044, 0.0434],
         [0.9305, 0.6740, 0.3352, 0.3030, 0.5063]],

        [[0.2776, 0.9571, 0.6311, 0.8931, 0.9123],
         [0.3689, 0.8993, 0.3627, 0.7342, 0.1456],
         [0.4310, 0.3680, 0.2311, 0.0096, 0.3824],
         [0.2775, 0.0749, 0.2761, 0.9329, 0.0941]],

        [[0.0121, 0.1008, 0.3266, 0.8738, 0.0712],
         [0.7653, 0.8295, 0.5083, 0.5273, 0.8029],
         [0.6561, 0.1950, 0.3236, 0.8100, 0.7557],
         [0.1459, 0.4602, 0.0489, 0.6679, 0.7645]]])

In [10]:
zero_tensor = torch.zeros(3,3)
ones_like_zeros = torch.ones_like(zero_tensor)
print(zero_tensor, zero_tensor.shape)
print(ones_like_zeros, ones_like_zeros.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([3, 3])


In [13]:
rand[0,0]

tensor([0.6418, 0.0201, 0.8284, 0.7265, 0.1945])

In [15]:
rand[0]

tensor([[0.6418, 0.0201, 0.8284, 0.7265, 0.1945],
        [0.4629, 0.1228, 0.4321, 0.3722, 0.1647],
        [0.6573, 0.4516, 0.7172, 0.3044, 0.0434],
        [0.9305, 0.6740, 0.3352, 0.3030, 0.5063]])

In [14]:
rand[:,0]

tensor([[0.6418, 0.0201, 0.8284, 0.7265, 0.1945],
        [0.2776, 0.9571, 0.6311, 0.8931, 0.9123],
        [0.0121, 0.1008, 0.3266, 0.8738, 0.0712]])

In [16]:
x = rand.detach()
x

tensor([[[0.6418, 0.0201, 0.8284, 0.7265, 0.1945],
         [0.4629, 0.1228, 0.4321, 0.3722, 0.1647],
         [0.6573, 0.4516, 0.7172, 0.3044, 0.0434],
         [0.9305, 0.6740, 0.3352, 0.3030, 0.5063]],

        [[0.2776, 0.9571, 0.6311, 0.8931, 0.9123],
         [0.3689, 0.8993, 0.3627, 0.7342, 0.1456],
         [0.4310, 0.3680, 0.2311, 0.0096, 0.3824],
         [0.2775, 0.0749, 0.2761, 0.9329, 0.0941]],

        [[0.0121, 0.1008, 0.3266, 0.8738, 0.0712],
         [0.7653, 0.8295, 0.5083, 0.5273, 0.8029],
         [0.6561, 0.1950, 0.3236, 0.8100, 0.7557],
         [0.1459, 0.4602, 0.0489, 0.6679, 0.7645]]])

In [17]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
print(rand1)
print(rand2)
torch.matmul(rand1,rand2)

tensor([0.8405, 0.8787, 0.0250, 0.5215, 0.9813])
tensor([0.7020, 0.3430, 0.6118, 0.2212, 0.5976])


tensor(1.6084)

In [18]:
rand1 = torch.rand(5,5)
rand2 = torch.rand(5,5)
print(rand1)
print(rand2)
torch.matmul(rand1,rand2)

tensor([[0.5543, 0.1033, 0.2247, 0.7767, 0.5889],
        [0.7814, 0.1214, 0.0625, 0.7766, 0.9022],
        [0.0385, 0.2596, 0.3917, 0.4641, 0.6748],
        [0.6808, 0.2408, 0.5362, 0.7695, 0.5026],
        [0.5335, 0.9519, 0.7008, 0.1688, 0.4424]])
tensor([[0.8105, 0.0056, 0.1918, 0.5199, 0.9639],
        [0.0039, 0.2544, 0.2182, 0.8946, 0.6763],
        [0.2741, 0.8053, 0.7335, 0.0835, 0.3746],
        [0.1092, 0.7228, 0.6986, 0.6586, 0.8445],
        [0.3403, 0.9025, 0.0581, 0.5023, 0.4027]])


tensor([[0.7965, 1.3032, 0.8704, 1.2067, 1.5814],
        [1.0428, 1.4612, 0.8171, 1.4848, 1.8779],
        [0.4199, 1.3260, 0.7147, 0.9296, 1.0231],
        [0.9548, 1.5067, 1.1431, 1.3734, 1.8722],
        [0.7972, 1.3307, 0.9676, 1.5208, 1.7412]])