In [2]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf

In [3]:
# Set random seed
np.random.seed(42)

In [24]:
# data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')

In [25]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [26]:
y

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [5]:
# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten

In [28]:
# One-hot encoding the output
y = np_utils.to_categorical(y)

In [29]:
y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [9]:
# Building the model
xor = Sequential()
xor.add(Dense(32, input_dim=X.shape[1]))
xor.add(Activation("tanh"))
xor.add(Dense(2))
xor.add(Activation("sigmoid"))

2022-08-26 14:42:09.286464: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-08-26 14:42:09.286532: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-26 14:42:09.286579: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (natasha-laptop): /proc/driver/nvidia/version does not exist


In [10]:
# compiling the model
xor.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])

In [11]:
# printing the model architecture
xor.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                96        
                                                                 
 activation (Activation)     (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 2)                 66        
                                                                 
 activation_1 (Activation)   (None, 2)                 0         
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [16]:
xor.fit(X, y, epochs=1000, verbose=0)

In [19]:
# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1], "\nLoss: ", score[0])

1/1 [==============================] - 0s 26ms/step - loss: 0.0016 - accuracy: 1.0000

Accuracy:  1.0 
Loss:  0.0016381675377488136


In [35]:
# Checking the predicted probabilities
print("Predicted probabilities:")
print(xor.predict(X))

Predicted probabilities:
[[0.9858093  0.095393  ]
 [0.02576068 0.93667114]
 [0.0498502  0.9706774 ]
 [0.9469583  0.02890718]]


In [36]:
# Checking the predictions
print("Predictions:")
print(np.argmax(xor.predict(X),axis=1))

Predictions:
[0 1 1 0]
